name: Build React

on:
  workflow_dispatch:


jobs:
  build-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend/test-app
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: actions/cache@v3
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run build

      - run: cp -r build/ ../../../backend/test-app/public

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::892369073500:instance-profile/elb-ec2
          role-session-name: eb-test-role
          aws-region: ap-northeast-1

      - name:  upload to s3
        run: |
          aws s3 cp ../../../backend/test-app/public s3://eb-test-public --delete
