name: create pull request

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'env name'
        required: true
        type: choice
        default: 'hoge'
        options:
          - 'hoge'
          - 'fuga'
          - 'piyo'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --base main --head env-${{ inputs.branch }} --title "deploy" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
