name: deploy application

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-react:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/frontend/test-app

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: make env file
        run: |
          touch .env
          echo "${{ secrets.REACT_ENV_FILE }}" > .env
      
      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: npm run build

      - run: cp -rf ./build/* ../../backend/test-app/public/

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/eb-test-github-actions-role
          role-session-name: eb-test-role
          aws-region: ap-northeast-1

      - name: upload to s3
        run: |
          aws s3 sync ../../backend/test-app/public s3://eb-test-public --delete
    
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/backend/test-app
    
    needs: build-react

    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/eb-test-github-actions-role
          role-session-name: eb-test-role
          aws-region: ap-northeast-1

      - name: get current version
        id: get_current_version
        run: |
          version=$(aws elasticbeanstalk describe-application-versions --application-name eb-test --query 'ApplicationVersions[0].VersionLabel' | sed -E 's/.*-//')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: increment version
        id: increment_version
        run: |
          version=${{ steps.get_current_version.outputs.version }}
          a=(${version//./ })
          echo "version=${a[0]}.${a[1]}.$((a[2]+1))" >> "$GITHUB_OUTPUT"
      
      - name: define artifact name
        id: define_artifact_name
        run: >
          echo
          "artifact_name=main-${{ steps.increment_version.outputs.version }}-${{ github.sha }}.zip"
          >> "$GITHUB_OUTPUT"
      
      - name: make artifact
        run: git archive --format=zip HEAD -o ${{ steps.define_artifact_name.outputs.artifact_name }}
      
      - name: upload artifact
        run: >
          aws s3 cp
          ${{ steps.define_artifact_name.outputs.artifact_name }}
          s3://${{ secrets.MAIN_ARTIFACT_BUCKET }}/main-artifact/${{ steps.define_artifact_name.outputs.artifact_name }}
      
      - name: make version
        run: >
          aws elasticbeanstalk create-application-version
          --application-name eb-test
          --version-label {{ steps.increment_version.outputs.version }}
          --source-bundle S3Bucket="${{ secrets.MAIN_ARTIFACT_BUCKET }}",S3Key="${{ steps.define_artifact_name.outputs.artifact_name }}"
      
      - name: set version
        run: >
          aws elasticbeanstalk update-environment
          --application-name eb-test
          --environment-name main
          --version-label {{ steps.increment_version.outputs.version }}

