name: increment version

on:
  workflow_dispatch:

jobs:

  increment:

    runs-on: ubuntu-latest

    steps:

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/eb-test-github-actions-role
          role-session-name: eb-test-role
          aws-region: ap-northeast-1
      
      - name: get current version
        id: get_current_version
        run: |
          version=$(aws elasticbeanstalk describe-application-versions --application-name eb-test --query 'ApplicationVersions[0].VersionLabel' | sed -E 's/.*-//')
          echo "::set-output name=version::$version"


      - name: increment version
        id: increment_version
        run: |
          version=${{ steps.get_current_version.outputs.version }}
          a=( ${$version//./ } )
          ((a[2]++))
          echo "::set-output name=version::${a[0]}.${a[1]}.${a[2]}"

      - name: version
        run: |
          echo ${{ steps.increment_version.outputs.version }}